Traceback (most recent call last):
  File "/home/ec2-user/autoflipp.online/flask-server/_VW_SEARCH.py", line 20, in <module>
    service = Service(ChromeDriverManager().install())
  File "/home/ec2-user/autoflipp.online/flask-server/venv/lib64/python3.9/site-packages/webdriver_manager/chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "/home/ec2-user/autoflipp.online/flask-server/venv/lib64/python3.9/site-packages/webdriver_manager/core/manager.py", line 41, in _get_driver_binary_path
    binary_path = self._cache_manager.save_file_to_cache(driver, file)
  File "/home/ec2-user/autoflipp.online/flask-server/venv/lib64/python3.9/site-packages/webdriver_manager/core/driver_cache.py", line 54, in save_file_to_cache
    files = self.unpack_archive(archive, path)
  File "/home/ec2-user/autoflipp.online/flask-server/venv/lib64/python3.9/site-packages/webdriver_manager/core/driver_cache.py", line 49, in unpack_archive
    return self._file_manager.unpack_archive(archive, path)
  File "/home/ec2-user/autoflipp.online/flask-server/venv/lib64/python3.9/site-packages/webdriver_manager/core/file_manager.py", line 57, in unpack_archive
    return self.__extract_zip(archive_file, target_dir)
  File "/home/ec2-user/autoflipp.online/flask-server/venv/lib64/python3.9/site-packages/webdriver_manager/core/file_manager.py", line 63, in __extract_zip
    archive = zip_class(archive_file.file_path)
  File "/usr/lib64/python3.9/zipfile.py", line 1268, in __init__
    self._RealGetContents()
  File "/usr/lib64/python3.9/zipfile.py", line 1335, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Traceback (most recent call last):
  File "/home/ec2-user/autoflipp.online/flask-server/_VW_SEARCH.py", line 87, in <module>
    driver.get(url)
  File "/home/ec2-user/autoflipp.online/flask-server/venv/lib64/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/home/ec2-user/autoflipp.online/flask-server/venv/lib64/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/ec2-user/autoflipp.online/flask-server/venv/lib64/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 297.669
  (Session info: chrome-headless-shell=126.0.6478.126)
Stacktrace:
#0 0x560e5d8c1c7a <unknown>
#1 0x560e5d5a4e2c <unknown>
#2 0x560e5d58c1a6 <unknown>
#3 0x560e5d58bd85 <unknown>
#4 0x560e5d589cc6 <unknown>
#5 0x560e5d58a33f <unknown>
#6 0x560e5d59ac67 <unknown>
#7 0x560e5d5b11be <unknown>
#8 0x560e5d5b68ab <unknown>
#9 0x560e5d58aa8a <unknown>
#10 0x560e5d5b103e <unknown>
#11 0x560e5d633679 <unknown>
#12 0x560e5d614363 <unknown>
#13 0x560e5d5e4247 <unknown>
#14 0x560e5d5e4b9e <unknown>
#15 0x560e5d88824b <unknown>
#16 0x560e5d88c2f1 <unknown>
#17 0x560e5d873afe <unknown>
#18 0x560e5d88ce52 <unknown>
#19 0x560e5d85879f <unknown>
#20 0x560e5d8b1638 <unknown>
#21 0x560e5d8b1810 <unknown>
#22 0x560e5d8c0dac <unknown>
#23 0x7fb44c69f7f2 start_thread

Button not found in this iframe, continuing to next iframe: Message: 
Stacktrace:
#0 0x55684257fc7a <unknown>
#1 0x556842262e2c <unknown>
#2 0x5568422af661 <unknown>
#3 0x5568422af751 <unknown>
#4 0x5568422f3f64 <unknown>
#5 0x5568422d25ed <unknown>
#6 0x5568422f1303 <unknown>
#7 0x5568422d2363 <unknown>
#8 0x5568422a2247 <unknown>
#9 0x5568422a2b9e <unknown>
#10 0x55684254624b <unknown>
#11 0x55684254a2f1 <unknown>
#12 0x556842531afe <unknown>
#13 0x55684254ae52 <unknown>
#14 0x55684251679f <unknown>
#15 0x55684256f638 <unknown>
#16 0x55684256f810 <unknown>
#17 0x55684257edac <unknown>
#18 0x7fc1d1a9f7f2 start_thread

Cookie consent has been accepted.
Data from 12 pages saved to 'VW_SEARCH.json'
